---
genome:
    name: Spom
    fasta: ../genome/S_pombe.ASM294v2.fa
    orf_annotation: ../genome/annotations/S_pombe_ORFs.bed
    transcript_annotation: ../genome/annotations/S_pombe_alltranscripts-adjustedTSS.bed

genic_windowsize: 30  # [INT] distance added to EACH side of the annotated TSS to determine genic regions
max_convergent_dist: 1000  # [INT] maximum distance downstream of genic sense TSS for an antisense peak to be considered convergent
max_divergent_dist: 500  # [INT] maximum distance upstream of genic sense TSS for an antisense peak to be considered divergent

gc_pct_window: 21  # window size for calculating GC percentage. Must be a positive odd integer.

motifs:
    build_motif_databases: True
    fimo_pval: 0.00001
    databases :
        - ../genomefiles_cerevisiae/motif_databases/yetfasco_all.meme
        - ../genomefiles_cerevisiae/motif_databases/YEASTRACT_20130918.meme
        - ../genomefiles_cerevisiae/motif_databases/macisaac_yeast.v1.meme
        - ../genomefiles_cerevisiae/motif_databases/scpd_matrix.meme
        - ../genomefiles_cerevisiae/motif_databases/SwissRegulon_s_cer.meme
        - ../genomefiles_cerevisiae/motif_databases/yeast_uniprobe_GR09.meme

threads: 4
